// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA79TFM6OHRAlMlvxcdOdn607V9EtPiGds',
    appId: '1:471953286442:web:97bb4ee2317b68f9642a53',
    messagingSenderId: '471953286442',
    projectId: 'tlu-flutter',
    authDomain: 'tlu-flutter.firebaseapp.com',
    storageBucket: 'tlu-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHE-Wqq5XFtnqy7rjDH-kNohGU3M5vvXI',
    appId: '1:471953286442:android:4f36d4c455667c30642a53',
    messagingSenderId: '471953286442',
    projectId: 'tlu-flutter',
    storageBucket: 'tlu-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnG73pSqskblxs3PVpnWsT7PAIJx4nAj4',
    appId: '1:471953286442:ios:c23118a0d0b2419b642a53',
    messagingSenderId: '471953286442',
    projectId: 'tlu-flutter',
    storageBucket: 'tlu-flutter.firebasestorage.app',
    iosBundleId: 'com.example.demoMyFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnG73pSqskblxs3PVpnWsT7PAIJx4nAj4',
    appId: '1:471953286442:ios:c23118a0d0b2419b642a53',
    messagingSenderId: '471953286442',
    projectId: 'tlu-flutter',
    storageBucket: 'tlu-flutter.firebasestorage.app',
    iosBundleId: 'com.example.demoMyFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA79TFM6OHRAlMlvxcdOdn607V9EtPiGds',
    appId: '1:471953286442:web:ec2fdc0735df7703642a53',
    messagingSenderId: '471953286442',
    projectId: 'tlu-flutter',
    authDomain: 'tlu-flutter.firebaseapp.com',
    storageBucket: 'tlu-flutter.firebasestorage.app',
  );
}
