// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWjrm3VAVlnTN2dtP-wv8nkEvP0ds28vw',
    appId: '1:448484821186:web:cf0951a2b7cdd6e956935b',
    messagingSenderId: '448484821186',
    projectId: 'tlu-firebase-44568',
    authDomain: 'tlu-firebase-44568.firebaseapp.com',
    storageBucket: 'tlu-firebase-44568.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5LxkcwsWkKqSqALU6IgzSwWCG_RQ-YOU',
    appId: '1:448484821186:android:2b9ea771d22646ca56935b',
    messagingSenderId: '448484821186',
    projectId: 'tlu-firebase-44568',
    storageBucket: 'tlu-firebase-44568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPC57DNDO6IiQIxKt2PzESkqvo-9JI6wg',
    appId: '1:448484821186:ios:0acd3e1dc5828b9056935b',
    messagingSenderId: '448484821186',
    projectId: 'tlu-firebase-44568',
    storageBucket: 'tlu-firebase-44568.firebasestorage.app',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPC57DNDO6IiQIxKt2PzESkqvo-9JI6wg',
    appId: '1:448484821186:ios:0acd3e1dc5828b9056935b',
    messagingSenderId: '448484821186',
    projectId: 'tlu-firebase-44568',
    storageBucket: 'tlu-firebase-44568.firebasestorage.app',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWjrm3VAVlnTN2dtP-wv8nkEvP0ds28vw',
    appId: '1:448484821186:web:d39627b21dfb503b56935b',
    messagingSenderId: '448484821186',
    projectId: 'tlu-firebase-44568',
    authDomain: 'tlu-firebase-44568.firebaseapp.com',
    storageBucket: 'tlu-firebase-44568.firebasestorage.app',
  );
}
